//
//  InterchangesDB.swift
//  LavoraMi
//
//  Created by Andrea Filice on 09/07/2026.
//

import Foundation
import MapKit

struct InterchangesDB {
    static let interchanges: [InterchangeInfo] = [
        .init(name: "Rho Fiera-Milano", lines: ["M1", "AV", "R21", "R23", "RE4", "RE5", "S5", "S6", "S11"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Lotto", lines: ["M1", "M5"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Cadorna FN", lines: ["M1", "M2", "R16", "R17", "R22", "R27", "RE1", "RE7", "S3", "S4", "MXP1"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Duomo", lines: ["M1", "M3"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "San Babila", lines: ["M1", "M4"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Porta Venezia", lines: ["M1", "S1", "S2", "S5", "S6", "S12", "S13"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Loreto", lines: ["M1", "M2"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Sesto 1° Maggio FS", lines: ["M1", "R13", "R14", "RE8", "S7", "S8", "S9", "S11"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Romolo", lines: ["M2", "R31", "S9", "S19"], typeOfInterchange: "lightrail.fill"),
        .init(name: "S. Ambrogio", lines: ["M2", "M4"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Porta Garibaldi", lines: ["M2", "M5", "AV", "R6", "R13", "R14", "R21", "R23", "R34", "RE2", "RE5", "RE6", "MXP1", "S1", "S2", "S5", "S6", "S7", "S8", "S9", "S11", "S12", "S13"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Centrale FS", lines: ["M2", "M3", "AV", "R4", "RE2", "RE4", "RE6", "RE8", "RE11", "RE13", "RE80", "MXP1"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Lambrate FS", lines: ["M2", "R4", "R6", "R7", "R34", "R38", "RE2", "RE6", "RE8", "RE11", "RE13", "S9"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Affori FN", lines: ["M3", "R16", "S2", "S4"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Zara", lines: ["M3", "M5"],typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Repubblica", lines: ["M3", "S1", "S2", "S5", "S6", "S12", "S13"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Lodi TIBB", lines: ["M3", "R31", "S9", "S19"], typeOfInterchange: "figure.walk"),
        .init(name: "Rogoredo FS", lines: ["M3", "AV", "R31", "R34", "R38", "RE8", "RE11", "RE13", "S1", "S2", "S9", "S12", "S13", "S19"], typeOfInterchange: "lightrail.fill"),
        .init(name: "San Cristoforo", lines: ["M4", "R31", "S9", "S19"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Sforza - Policlinico", lines: ["M3", "M4"], typeOfInterchange: "figure.walk"),
        .init(name: "Dateo", lines: ["M4", "S1", "S2", "S5", "S6", "S12", "S13"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Stazione Forlanini", lines: ["M4", "R38", "RE8", "RE13", "S5", "S6", "S9"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Linate Aereoporto", lines: ["Aereoporto", "M4"], typeOfInterchange: "airplane.departure"),
        .init(name: "Domodossola FN", lines: ["M5", "R16", "R17", "R22", "R27", "RE1", "RE7", "MXP2", "S3", "S4"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Como S. Giovanni", lines: ["S10", "S11", "S40", "RE80"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Mendrisio", lines: ["S10", "S40", "S50", "RE80"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Biasca", lines: ["S10", "S50"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Varese", lines: ["S5", "S40", "S50"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Gallarate", lines: ["S30", "S50"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Busto Arsizio Nord", lines: ["S50", "MXP1", "MXP2"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Milano Bovisa", lines: ["S1", "S2", "S3", "S4", "S12", "S13", "MXP1", "MXP2"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Saronno", lines: ["S1", "S3", "S9", "MXP1", "MXP2"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Monza", lines: ["S7", "S8", "S9", "S11", "RE80"], typeOfInterchange: "lightrail.fill")
    ]
    
    static let interchangesTrams: [InterchangeInfo] = [
        .init(name: "Certosa FS", lines: ["1", "12", "RE13", "S5", "S6", "S11"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Piazza Firenze", lines: ["1", "14", "19"], typeOfInterchange: "tram.fill"),
        .init(name: "Domodossola FN", lines: ["M5", "1", "19", "R16", "R17", "R22", "R27", "RE1", "RE7", "MXP2", "S3", "S4"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Cadorna FN", lines: ["M1", "M2", "1", "2", "R16", "R17", "R22", "R27", "RE1", "RE7", "S3", "S4", "MXP1"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Cairoli M1", lines: ["M1", "1", "2", "4"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Cordusio M1", lines: ["M1", "1", "12", "14", "16", "19"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Montenapoleone M3", lines: ["M3", "1"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Turati M3", lines: ["M3", "1"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Repubblica M3", lines: ["M3", "1", "9", "33", "S1", "S2", "S5", "S6", "S12", "S13"], typeOfInterchange: "lightrail.fill"),
        .init(name: "V.Le Tunisia", lines: ["1", "5", "33"], typeOfInterchange: "tram.fill"),
        .init(name: "Caiazzo M2", lines: ["M2", "1"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Porta Genova M2", lines: ["M2", "2", "3", "9", "10"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "V.Le Coni Zugna Via Solari", lines: ["2", "10", "14"], typeOfInterchange: "tram.fill"),
        .init(name: "Conciliazione M1", lines: ["M1", "2", "10"], typeOfInterchange: "tram.fill"),
        .init(name: "Largo Quinto Alpini", lines: ["1", "2", "10", "19"], typeOfInterchange: "tram.fill"),
        .init(name: "Lanza M2", lines: ["M2", "2", "4", "12", "14"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Via Farini Via Ferrari", lines: ["2", "4", "10", "33"], typeOfInterchange: "tram.fill"),
        .init(name: "Piazza Abbiategrasso M2", lines: ["M2", "3", "15"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "P.Le Cantore", lines: ["2", "3", "9", "10", "14"], typeOfInterchange: "tram.fill"),
        .init(name: "Maciachini M3", lines: ["M3", "4"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Ca' Granda M5", lines: ["M5", "4", "5", "7", "31"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Bicocca M5", lines: ["M5", "4", "7", "31"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Ponale M5", lines: ["M5", "4", "7", "31"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Bignami M5", lines: ["M5", "4", "7", "31"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Istria M5", lines: ["M5", "5", "7", "31"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Marche M5", lines: ["M5", "5", "7", "31"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Centrale FS", lines: ["M2", "M3", "5", "9", "10", "AV", "R4", "RE2", "RE4", "RE6", "RE8", "RE11", "RE13", "RE80", "MXP1"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Zara M3 M5", lines: ["M3", "M5", "7", "31"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Precotto M1", lines: ["M1", "7"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Porta Romana M3", lines: ["M3", "9"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Porta Venezia M1", lines: ["M1", "9", "S1", "S2", "S5", "S6", "S12", "S13"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Porta Venezia V.Le Tunisia", lines: ["M1", "5", "33"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "P.Za Otto Novembre", lines: ["5", "33", "S1", "S2", "S5", "S6", "S12", "S13"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Garibaldi FS", lines: ["M2", "M5", "10", "33", "AV", "R6", "R13", "R14", "R21", "R23", "R34", "RE2", "RE5", "RE6", "MXP1", "S1", "S2", "S5", "S6", "S7", "S8", "S9", "S11", "S12", "S13"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Monumentale M5", lines: ["M5", "10"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Coni Zugna M4", lines: ["M4", "10"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Repetti M4", lines: ["M4", "12", "27"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Stazione Forlanini FS", lines: ["M4", "12", "27", "R38", "RE8", "RE13", "S5", "S6", "S9"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Piazza Cinque Giornate", lines: ["9", "12", "19", "27"], typeOfInterchange: "tram.fill"),
        .init(name: "Piazza Ascoli", lines: ["5", "19", "33"], typeOfInterchange: "tram.fill"),
        .init(name: "Missori M3", lines: ["M3", "12", "15", "16", "19", "24"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Duomo M1 M3", lines: ["M1", "M3", "2", "3", "12", "14", "15", "16", "19"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Cenisio M5", lines: ["M5", "12", "14"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Santa Sofia M4", lines: ["M4", "15"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "S. Siro Stadio M5", lines: ["M5", "16"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "S. Siro Ippodromo M5", lines: ["M5", "16"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "De Angeli M1", lines: ["M1", "16"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Sforza - Policlinico M4", lines: ["M4", "16", "24"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Crocetta M3", lines: ["M3", "16", "24"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Lambrate FS", lines: ["M2", "19", "R4", "R6", "R7", "R34", "R38", "RE2", "RE6", "RE8", "RE11", "RE13", "S9"], typeOfInterchange: "lightrail.fill"),
        .init(name: "Via Larga", lines: ["12", "19", "24"], typeOfInterchange: "tram.fill"),
        .init(name: "P.Le Lagosta", lines: ["7", "31", "33"], typeOfInterchange: "tram.fill"),
        .init(name: "Porta Romana M3", lines: ["M3", "9"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Tricolore M4", lines: ["M4", "9", "19"], typeOfInterchange: "tram.fill.tunnel")
    ]
    
    static let interchangesFilobus: [InterchangeInfo] = [
        .init(name: "Lodi M3", lines: ["M3", "NM3", "90", "91", "92"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "V.Le Isonzo Via Ripamonti", lines: ["24", "90", "91", "N24"], typeOfInterchange: "tram.fill"),
        .init(name: "Tibaldi", lines: ["S9", "S19", "R31", "15", "59", "90", "91"], typeOfInterchange: "lightrail"),
        .init(name: "V.Le Tibaldi Via Meda", lines: ["3", "59", "71", "90", "91", "N15"], typeOfInterchange: "tram.fill"),
        .init(name: "Romolo M2", lines: ["M2", "NM2", "S9", "S19", "R31", "47", "71", "90", "91", "324", "325", "z553"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Ponte Guido Crepax", lines: ["2", "90", "91", "324", "325"], typeOfInterchange: "tram.fill"),
        .init(name: "Bolivar M4", lines: ["M4", "NM4", "58", "90", "91"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "P.Le Brescia", lines: ["16", "90", "91"], typeOfInterchange: "tram.fill"),
        .init(name: "Lotto M1 M5", lines: ["M1", "NM1", "M5", "48", "49", "68", "78", "90", "91", "98"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "P.Le Cuoco", lines: ["16", "90", "91", "93"], typeOfInterchange: "tram.fill"),
        .init(name: "Porta Vittoria FS", lines: ["S1", "S2", "S5", "S6", "S12", "S13", "90", "91", "93"], typeOfInterchange: "lightrail"),
        .init(name: "V.Le Campania V.Le Corsica", lines: ["12", "27", "90", "91", "93", "973", "N27"], typeOfInterchange: "tram.fill"),
        .init(name: "Susa M4", lines: ["M4", "NM4", "38", "54", "90", "91"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "P.Za Ferravilla", lines: ["5", "90", "91"], typeOfInterchange: "tram.fill"),
        .init(name: "V.Le Romagna Via Pascoli", lines: ["19", "33", "62", "90", "91"], typeOfInterchange: "tram.fill"),
        .init(name: "V.Le Romagna Piola M2", lines: ["M2", "NM2", "39", "62", "90", "91"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Loreto M1 M2", lines: ["M1", "NM1", "M2", "NM2", "39", "55", "56", "90", "91", "174"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Caiazzo M2", lines: ["M2", "NM2", "1", "90", "91", "92"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Stazione Centrale Via Tonale", lines: ["5", "10", "42", "90", "91", "92"], typeOfInterchange: "tram.fill"),
        .init(name: "Sondrio M3", lines: ["M3", "NM3", "90", "91", "92"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Zara M3 M5", lines: ["M3", "NM3", "M5", "7", "31", "51", "60", "82", "90", "91", "92", "166"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Via Farini V.Le Stelvio", lines: ["2", "4", "70", "82", "90", "91", "92"], typeOfInterchange: "tram.fill"),
        .init(name: "Mac Mahon / M.Te Ceneri", lines: ["12", "90", "91"], typeOfInterchange: "tram.fill"),
        .init(name: "V.Le Certosa V.Le Serra", lines: ["1", "14", "69", "90", "91"], typeOfInterchange: "tram.fill"),
        .init(name: "V.Le Umbria Via Comelico", lines: ["16", "92"], typeOfInterchange: "tram.fill"),
        .init(name: "P.Za Emilia", lines: ["12", "27", "973", "92"], typeOfInterchange: "tram.fill"),
        .init(name: "Dateo FS M4", lines: ["M4", "NM4", "S1", "S2", "S5", "S6", "S12", "S13", "54", "61", "92"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "P.Za Ascoli", lines: ["5", "19", "33", "60", "61", "92"], typeOfInterchange: "tram.fill"),
        .init(name: "Lancetti FS", lines: ["S1", "S2", "S5", "S6", "S12", "S13", "2", "92"], typeOfInterchange: "lightrail"),
        .init(name: "Via Varè (Bovisa FN)", lines: ["R16", "R17", "R22", "R27", "RE1", "RE7", "RE13", "MXP1", "MXP2", "S1", "S2", "S3", "S4", "S12", "S13", "92"], typeOfInterchange: "lightrail"),
        .init(name: "Corvetto M3", lines: ["M3", "NM3", "84", "93"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Argonne M4", lines: ["M4", "NM4", "38", "54", "93"], typeOfInterchange: "tram.fill.tunnel"),
        .init(name: "Via B. Angelico Via Aselli", lines: ["5", "93"], typeOfInterchange: "tram.fill"),
        .init(name: "Via Bassini Via Golgi", lines: ["19", "33", "45", "93", "175"], typeOfInterchange: "tram.fill"),
        .init(name: "Lambrate FS M2", lines: ["M2", "NM2", "R4", "R6", "R7", "R34", "R38", "RE2", "RE6", "RE8", "RE11", "RE13", "S9", "19", "39", "45", "54", "81", "93", "175", "924"], typeOfInterchange: "lightrail")
    ]

    static let interchangesMetro: [InterchangeInfo] = [
        // M1 - Main
        .init(name: "Sesto 1° Maggio FS", lines: ["M1", "NM1", "S7", "S8", "S9", "S11", "R13", "R14", "RE8", "700", "702", "712", "727", "729"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 19),
        .init(name: "Sesto Rondò", lines: ["M1", "NM1", "700", "701", "708", "713"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 18),
        .init(name: "Sesto Marelli", lines: ["M1", "NM1", "51", "81", "87"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 17),
        .init(name: "Villa S. Giovanni", lines: ["M1", "NM1", "51", "81", "87"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 16),
        .init(name: "Precotto", lines: ["M1", "NM1", "7", "51", "86", "174"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 15),
        .init(name: "Gorla", lines: ["M1", "NM1", "44", "174"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 14),
        .init(name: "Turro", lines: ["M1", "NM1", "44", "174"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 13),
        .init(name: "Rovereto", lines: ["M1", "NM1", "174"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 12),
        .init(name: "Pasteur", lines: ["M1", "NM1"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 11),
        .init(name: "Loreto M1 M2", lines: ["M1", "NM1", "M2", "NM2", "39", "55", "56", "Filobus 90", "Filobus 91"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 10),
        .init(name: "Lima", lines: ["M1", "NM1", "60", "81", "N25", "N26"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 9),
        .init(name: "Porta Venezia FS", lines: ["M1", "NM1", "S1", "S2", "S5", "S6", "S12", "S13", "5", "9", "33"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 8),
        .init(name: "Palestro", lines: ["M1", "NM1"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 7),
        .init(name: "San Babila M1 M4", lines: ["M1", "NM1", "M4", "NM4", "NM3", "61", "84"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 6),
        .init(name: "Duomo M1 M3", lines: ["M1", "NM1", "M3", "NM3", "12", "15", "16", "19", "60", "61", "N15", "N24", "N27"], typeOfInterchange: "building.columns.fill", branch: "Main", lineOrder: 5),
        .init(name: "Cordusio", lines: ["M1", "NM1", "1", "12", "16", "19"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 4),
        .init(name: "Cairoli", lines: ["M1", "NM1", "NM2", "1", "2", "4", "50", "96", "97"], typeOfInterchange: "building.columns.fill", branch: "Main", lineOrder: 3),
        .init(name: "Cadorna FN M1 M2", lines: ["M1", "NM1", "M2", "NM2", "S3", "S4", "R22", "R27", "RE1", "RE7", "MXP2", "1", "2", "50", "96", "97", "z602", "z603", "z6C3", "N25", "N26"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 2),
        .init(name: "Conciliazione", lines: ["M1", "NM1", "2", "10", "67", "68", "N26"], typeOfInterchange: "tram.fill", branch: "Main", lineOrder: 1),
        .init(name: "Pagano", lines: ["M1", "NM1", "67", "85"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 0),
        
        // M1 - Rho Fiera-Milano
        .init(name: "Buonarroti", lines: ["M1", "NM1"], typeOfInterchange: "tram.fill.tunnel", branch: "Rho Fiera-Milano", lineOrder: 9),
        .init(name: "Amendola", lines: ["M1", "NM1", "68"], typeOfInterchange: "tram.fill.tunnel", branch: "Rho Fiera-Milano", lineOrder: 8),
        .init(name: "Lotto M1 M5", lines: ["M1", "NM1", "M5", "48", "49", "68", "78", "Filobus 90", "Filobus 91", "98"], typeOfInterchange: "tram.fill.tunnel", branch: "Rho Fiera-Milano", lineOrder: 7),
        .init(name: "QT8", lines: ["M1", "NM1", "68", "560"], typeOfInterchange: "tram.fill.tunnel", branch: "Rho Fiera-Milano", lineOrder: 6),
        .init(name: "Lampugnano", lines: ["M1", "NM1", "68"], typeOfInterchange: "tram.fill.tunnel", branch: "Rho Fiera-Milano", lineOrder: 5),
        .init(name: "Uruguay", lines: ["M1", "40", "68", "69"], typeOfInterchange: "tram.fill.tunnel", branch: "Rho Fiera-Milano", lineOrder: 4),
        .init(name: "Bonola", lines: ["M1", "40", "64", "68", "69"], typeOfInterchange: "tram.fill.tunnel", branch: "Rho Fiera-Milano", lineOrder: 3),
        .init(name: "S. Leonardo", lines: ["M1", "NM1"], typeOfInterchange: "tram.fill.tunnel", branch: "Rho Fiera-Milano", lineOrder: 2),
        .init(name: "Molino Dorino", lines: ["M1", "NM1", "35", "69", "80", "424", "528", "z601", "z617", "z620", "z621", "z649"], typeOfInterchange: "bus.fill", branch: "Rho Fiera-Milano", lineOrder: 1),
        .init(name: "Rho Fiera-Milano", lines: ["M1", "S5", "S6", "S11", "R21", "R23", "RE4", "RE5", "RE80", "542", "561"], typeOfInterchange: "lightrail", branch: "Rho Fiera-Milano", lineOrder: 0),
        
        // M1 - Bisceglie
        .init(name: "Wagner", lines: ["M1", "NM1", "67"], typeOfInterchange: "tram.fill.tunnel", branch: "Bisceglie", lineOrder: 6),
        .init(name: "De Angeli", lines: ["M1", "NM1", "16", "63", "80"], typeOfInterchange: "tram.fill.tunnel", branch: "Bisceglie", lineOrder: 5),
        .init(name: "Gambara", lines: ["M1", "NM1"], typeOfInterchange: "tram.fill.tunnel", branch: "Bisceglie", lineOrder: 4),
        .init(name: "Bande Nere", lines: ["M1", "NM1", "67", "98"], typeOfInterchange: "tram.fill.tunnel", branch: "Bisceglie", lineOrder: 3),
        .init(name: "Primaticcio", lines: ["M1", "NM1", "63", "64"], typeOfInterchange: "tram.fill.tunnel", branch: "Bisceglie", lineOrder: 2),
        .init(name: "Inganni", lines: ["M1", "NM1", "49", "58", "63", "67"], typeOfInterchange: "tram.fill.tunnel", branch: "Bisceglie", lineOrder: 1),
        .init(name: "Bisceglie", lines: ["M1", "NM1", "47", "58", "63", "76", "78", "321", "322", "323", "327", "433", "z551"], typeOfInterchange: "bus.fill", branch: "Bisceglie", lineOrder: 0),
        
        // M2 - Gessate
        .init(name: "Gessate", lines: ["M2", "z404", "z405"], typeOfInterchange: "tram.fill.tunnel", branch: "Gessate", lineOrder: 0),
        .init(name: "Cascina Antonietta", lines: ["M2"], typeOfInterchange: "tram.fill.tunnel", branch: "Gessate", lineOrder: 1),
        .init(name: "Gorgonzola", lines: ["M2", "z403", "z407", "z411", "z419"], typeOfInterchange: "tram.fill.tunnel", branch: "Gessate", lineOrder: 2),
        .init(name: "Villa Pompea", lines: ["M2"], typeOfInterchange: "tram.fill.tunnel", branch: "Gessate", lineOrder: 3),
        .init(name: "Bussero", lines: ["M2"], typeOfInterchange: "tram.fill.tunnel", branch: "Gessate", lineOrder: 4),
        .init(name: "Cassina de Pecchi", lines: ["M2"], typeOfInterchange: "tram.fill.tunnel", branch: "Gessate", lineOrder: 5),
        .init(name: "Villa Fiorita", lines: ["M2", "z401"], typeOfInterchange: "tram.fill.tunnel", branch: "Gessate", lineOrder: 6),
        .init(name: "Cernusco Sul Naviglio", lines: ["M2", "z402"], typeOfInterchange: "tram.fill.tunnel", branch: "Gessate", lineOrder: 7),
        .init(name: "Cascina Burrona", lines: ["M2", "924"], typeOfInterchange: "tram.fill.tunnel", branch: "Gessate", lineOrder: 8),
        .init(name: "Vimodrone", lines: ["M2"], typeOfInterchange: "tram.fill.tunnel", branch: "Gessate", lineOrder: 9),
        
        // M2 - Cologno Nord
        .init(name: "Cologno Nord", lines: ["M2", "701", "702", "707"], typeOfInterchange: "tram.fill.tunnel", branch: "Cologno Nord", lineOrder: 0),
        .init(name: "Cologno Centro", lines: ["M2", "702", "707"], typeOfInterchange: "tram.fill.tunnel", branch: "Cologno Nord", lineOrder: 1),
        .init(name: "Cologno Sud", lines: ["M2", "701", "707", "709"], typeOfInterchange: "tram.fill.tunnel", branch: "Cologno Nord", lineOrder: 2),
        
        // M2 - Main
        .init(name: "Cascina Gobba", lines: ["M2", "NM2", "44", "54", "86", "925"], typeOfInterchange: "bus.fill", branch: "Main", lineOrder: 0),
        .init(name: "Cimiano", lines: ["M2", "NM2", "53", "54"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 1),
        .init(name: "Udine", lines: ["M2", "NM2", "53", "54", "55", "175", "925"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 2),
        .init(name: "Lambrate FS", lines: ["M2", "NM2", "S9", "R4", "R6", "R7", "R34", "R38", "RE2", "RE6", "RE8", "RE11", "RE13", "19", "39", "45", "54", "81", "93", "175", "924"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 3),
        .init(name: "Piola", lines: ["M2", "NM2", "39", "62", "Filobus 90", "Filobus 91"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 4),
        .init(name: "Loreto M1 M2", lines: ["M2", "NM2", "M1", "NM1", "39", "55", "56", "Filobus 90", "Filobus 91"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 5),
        .init(name: "Caiazzo M2", lines: ["M2", "NM2", "1", "Filobus 90", "Filobus 91", "Filobus 92"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 6),
        .init(name: "Centrale FS M2 M3", lines: ["M2", "NM2", "M3", "NM3", "AV", "R4", "RE2", "RE4", "RE6", "RE8", "RE11", "RE13", "MXP1", "RE80", "5", "9", "10", "42", "60", "81", "87", "Filobus 90", "Filobus 91", "Filobus 92", "728", "N25", "N26"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 7),
        .init(name: "Gioia", lines: ["M2", "NM2", "43", "N26"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 8),
        .init(name: "Garibaldi FS M2 M5", lines: ["M2", "NM2", "M5", "S1", "S2", "S5", "S6", "S7", "S8", "S9", "S11", "S12", "S13", "AV", "R6", "R13", "R14", "R21", "R23", "R34", "RE2", "RE5", "RE6", "RE13", "MXP1", "10", "33", "N25", "N26"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 9),
        .init(name: "Moscova", lines: ["M2", "43", "84"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 10),
        .init(name: "Lanza", lines: ["M2", "NM2", "2", "4", "12", "14", "57", "97"], typeOfInterchange: "tram.fill", branch: "Main", lineOrder: 11),
        .init(name: "Cadorna FN M1 M2", lines: ["M2", "NM2", "M1", "NM1", "S3", "S4", "R22", "R27", "RE1", "RE7", "MXP2", "1", "2", "50", "96", "97", "z602", "z603", "z6C3", "N25", "N26"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 12),
        .init(name: "S. Ambrogio M2 M4", lines: ["M2", "NM2", "M4", "NM4", "50", "96", "97"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 13),
        .init(name: "S. Agostino", lines: ["M2", "NM2", "NM4"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 14),
        .init(name: "Porta Genova", lines: ["M2", "NM2", "2", "3", "9", "10", "74", "N25", "N26"], typeOfInterchange: "building.columns.fill", branch: "Main", lineOrder: 15),
        .init(name: "Romolo FS", lines: ["M2", "NM2", "S9", "S19", "R31", "47", "Filobus 90", "Filobus 91", "71", "324", "325", "z553"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 16),
        .init(name: "Famagosta", lines: ["M2", "NM2", "46", "59", "71", "74", "95", "98", "z501", "z509", "z510", "z515", "z516"], typeOfInterchange: "bus.fill", branch: "Main", lineOrder: 17),
        
        // M2 - P.Za Abbiategrasso
        .init(name: "P.Za Abbiategrasso", lines: ["M2", "NM2", "3", "15", "65", "79", "230", "N15"], typeOfInterchange: "tram.fill.tunnel", branch: "P.Za Abbiategrasso", lineOrder: 0),
        
        // M2 - Assago Milanofiori Forum
        .init(name: "Assago Milanofiori Forum", lines: ["M2", "321", "328", "352", "z501", "z510", "z515"], typeOfInterchange: "tram.fill.tunnel", branch: "Assago Milanofiori Forum", lineOrder: 0),
        .init(name: "Assago Milanofiori Nord", lines: ["M2"], typeOfInterchange: "tram.fill.tunnel", branch: "Assago Milanofiori Forum", lineOrder: 1),
        
        // M3 - Main
        .init(name: "Comasina", lines: ["M3", "NM3", "35", "41", "52", "83", "89", "165", "705", "729"], typeOfInterchange: "bus.fill", branch: "Main", lineOrder: 0),
        .init(name: "Affori FN", lines: ["M3", "NM3", "S2", "S4", "R16", "35", "40", "41", "52", "70"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 1),
        .init(name: "Affori Centro", lines: ["M3", "NM3", "70"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 2),
        .init(name: "Dergano", lines: ["M3", "NM3", "70"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 3),
        .init(name: "Maciachini", lines: ["M3", "NM3", "2", "4", "70"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 4),
        .init(name: "Zara", lines: ["M3", "NM3", "M5", "7", "31", "51", "60", "82", "Filobus 90", "Filobus 91", "Filobus 92", "166"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 5),
        .init(name: "Sondrio", lines: ["M3", "NM3", "43", "81", "Filobus 90", "Filobus 91", "Filobus 92"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 6),
        .init(name: "Centrale FS M2 M3", lines: ["M3", "NM3", "M2", "NM2", "AV", "R4", "RE2", "RE4", "RE6", "RE8", "RE11", "RE13", "MXP1", "RE80", "5", "9", "10", "42", "60", "81", "87", "Filobus 90", "Filobus 91", "Filobus 92", "728", "N25", "N26"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 7),
        .init(name: "Repubblica FS", lines: ["M3", "NM3", "S1", "S2", "S5", "S6", "S12", "S13", "1", "9", "33", "43"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 8),
        .init(name: "Turati", lines: ["M3", "NM3", "1", "43", "84"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 9),
        .init(name: "Montenapoleone", lines: ["M3", "1", "96"], typeOfInterchange: "building.columns.fill", branch: "Main", lineOrder: 10),
        .init(name: "Duomo M1 M3", lines: ["M3", "NM3", "M1", "NM1", "12", "15", "16", "19", "60", "61", "N15", "N24", "N27"], typeOfInterchange: "building.columns.fill", branch: "Main", lineOrder: 11),
        .init(name: "Missori", lines: ["M3", "NM3", "M4", "12", "15", "16", "19", "24", "N15", "N24"], typeOfInterchange: "building.columns.fill", branch: "Main", lineOrder: 12),
        .init(name: "Crocetta", lines: ["M3", "NM3", "16", "24", "65", "N24"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 13),
        .init(name: "Porta Romana", lines: ["M3", "NM3", "9", "62", "65", "N26"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 14),
        .init(name: "Lodi TIBB", lines: ["M3", "NM3", "S9", "S19", "R31", "65", "Filobus 90", "Filobus 91", "Filobus 92"], typeOfInterchange: "figure.walk", branch: "Main", lineOrder: 15),
        .init(name: "Brenta", lines: ["M3", "NM3", "34", "65"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 16),
        .init(name: "Corvetto", lines: ["M3", "NM3", "84", "Filobus 93", "95"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 17),
        .init(name: "Porto di Mare", lines: ["M3", "NM3", "77", "95"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 18),
        .init(name: "Rogoredo FS", lines: ["M3", "NM3", "S1", "S2", "S9", "S12", "S13", "S19", "R31", "R34", "R38", "RE8", "RE11", "RE13", "77", "88", "95", "140"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 19),
        .init(name: "San Donato", lines: ["M3", "NM3", "45", "77", "121", "130", "132", "901", "902", "903", "z410", "z411", "z412", "z413", "z415", "z420"], typeOfInterchange: "bus.fill", branch: "Main", lineOrder: 20),
        
        // M4 - Main
        .init(name: "Linate Aereoporto", lines: ["M4", "NM4", "183", "901", "903", "923", "973", "z409"], typeOfInterchange: "airplane.departure", branch: "Main", lineOrder: 0),
        .init(name: "Repetti", lines: ["M4", "NM4", "12", "27", "45", "175", "N27"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 1),
        .init(name: "Stazione Forlanini FS", lines: ["M4", "NM4", "S5", "S6", "S9", "R38", "RE8", "RE13", "12", "27", "45", "175", "973", "N27"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 2),
        .init(name: "Argonne", lines: ["M4", "NM4", "38", "45", "54", "Filobus 93", "175"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 3),
        .init(name: "Susa", lines: ["M4", "NM4", "38", "54", "Filobus 90", "Filobus 91"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 4),
        .init(name: "Dateo FS", lines: ["M4", "NM4", "S1", "S2", "S5", "S6", "S12", "S13", "54", "61", "Filobus 92"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 5),
        .init(name: "Tricolore", lines: ["M4", "NM4", "9", "19", "61"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 6),
        .init(name: "San Babila M1 M4", lines: ["M4", "NM4", "M1", "NM1", "NM3", "61", "84"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 7),
        .init(name: "Sforza - Policlinico", lines: ["M4", "NM4", "M3", "NM3", "16", "24", "65", "96", "97", "N24"], typeOfInterchange: "figure.walk", branch: "Main", lineOrder: 8),
        .init(name: "Santa Sofia", lines: ["M4", "NM4", "15", "96", "97", "N15"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 9),
        .init(name: "Vetra", lines: ["M4", "NM4", "3", "96", "97"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 10),
        .init(name: "De Amicis", lines: ["M4", "NM4", "NM2", "2", "14", "96", "97"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 11),
        .init(name: "S. Ambrogio M2 M4", lines: ["M4", "NM4", "M2", "NM2", "50", "96", "97"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 12),
        .init(name: "Coni Zugna", lines: ["M4", "NM4", "2", "10", "58"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 13),
        .init(name: "California", lines: ["M4", "NM4", "58", "68"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 14),
        .init(name: "Bolivar", lines: ["M4", "NM4", "58", "85", "Filobus 90", "Filobus 91"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 15),
        .init(name: "Tolstoj", lines: ["M4", "NM4", "58"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 16),
        .init(name: "Frattini", lines: ["M4", "NM4", "58", "98"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 17),
        .init(name: "Gelsomini", lines: ["M4", "NM4", "50", "58", "64"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 18),
        .init(name: "Segneri", lines: ["M4", "NM4", "50", "64"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 19),
        .init(name: "San Cristoforo FS", lines: ["M4", "NM4", "S9", "S19", "R31", "47", "49", "95", "324", "325", "326", "351", "z553"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 20),
        
        // M5 - Main
        .init(name: "Bignami", lines: ["M5", "4", "31", "713", "728"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 0),
        .init(name: "Ponale", lines: ["M5", "4", "31", "51", "172"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 1),
        .init(name: "Bicocca", lines: ["M5", "4", "7", "31", "52", "172", "783"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 2),
        .init(name: "Ca' Granda", lines: ["M5", "4", "5", "7", "31", "86", "172"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 3),
        .init(name: "Istria", lines: ["M5", "5", "7", "31", "42"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 4),
        .init(name: "Marche", lines: ["M5", "5", "7", "31"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 5),
        .init(name: "Isola", lines: ["M5"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 6),
        .init(name: "Garibaldi FS M2 M5", lines: ["M5", "M2", "NM2", "S1", "S2", "S5", "S6", "S7", "S8", "S9", "S11", "S12", "S13", "AV", "R6", "R13", "R14", "R21", "R23", "R34", "RE2", "RE5", "RE6", "RE13", "MXP1", "10", "33", "N25", "N26"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 7),
        .init(name: "Monumentale", lines: ["M5", "10", "12", "14", "70"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 8),
        .init(name: "Cenisio", lines: ["M5", "12", "14"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 9),
        .init(name: "Gerusalemme", lines: ["M5"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 10),
        .init(name: "Domodossola FN", lines: ["M5", "S3", "S4", "R16", "R17", "R22", "R27", "RE1", "RE7", "MXP2", "1", "19"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 11),
        .init(name: "Tre Torri", lines: ["M5"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 12),
        .init(name: "Lotto M1 M5", lines: ["M5", "M1", "NM1", "48", "49", "68", "78", "Filobus 90", "Filobus 91", "98"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 13),
        .init(name: "Portello", lines: ["M5", "48", "78"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 14),
        .init(name: "San Siro Ippodromo", lines: ["M5", "16"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 15),
        .init(name: "San Siro Stadio", lines: ["M5", "Stadio", "16", "49"], typeOfInterchange: "stadium.fill", branch: "Main", lineOrder: 16),
    ]
    
    static let suburbanInterchanges: [InterchangeInfo] = [
        // SUBURBAN LINES
        
        // Suburbano S1
        .init(name: "Saronno", lines: ["S1", "S3", "S9", "R17", "R22", "R27", "RE1", "RE7", "RE13", "MXP1", "MXP2"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 0),
        .init(name: "Saronno Sud", lines: ["S1", "S3", "S9"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 1),
        .init(name: "Caronno Pertusella", lines: ["S1", "S3"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 2),
        .init(name: "Cesate", lines: ["S1", "S3"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 3),
        .init(name: "Garbagnate Milanese", lines: ["S1", "S3", "S13", "RE13"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 4),
        .init(name: "Garbagnate Parco Delle Groane", lines: ["S1", "S3"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 5),
        .init(name: "Bollate Nord", lines: ["S1", "S3"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 6),
        .init(name: "Bollate Centro", lines: ["S1", "S3", "S13", "RE13"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 7),
        .init(name: "Novate Milanese", lines: ["S1", "S3"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 8),
        .init(name: "Milano Quarto Oggiaro", lines: ["S1", "S3", "40"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 9),
        .init(name: "Milano Bovisa", lines: ["S1", "S2", "S3", "S4", "S12", "S13", "R16", "R17", "R22", "R27", "RE1", "RE7", "RE13", "MXP1", "MXP2", "82", "Filobus 92"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 10),
        .init(name: "Milano Lancetti", lines: ["S1", "S2", "S5", "S6", "S12", "S13", "2", "Filobus 92"], typeOfInterchange: "tram.fill", branch: "Main", lineOrder: 11),
        .init(name: "Milano Porta Garibaldi", lines: ["S1", "S2", "S5", "S6", "S7", "S8", "S9", "S11", "S12", "S13", "AV", "R6", "R13", "R14", "R21", "R23", "R34", "RE2", "RE5", "RE6", "RE13", "MXP1", "M2", "NM2", "M5", "10", "33", "N25", "N26"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 12),
        .init(name: "Milano Repubblica", lines: ["S1", "S2", "S5", "S6", "S12", "S13", "M3", "NM3", "1", "9", "33", "43"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 13),
        .init(name: "Milano Porta Venezia", lines: ["S1", "S2", "S5", "S6", "S12", "S13", "M1", "NM1", "5", "9", "33"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 14),
        .init(name: "Milano Dateo", lines: ["S1", "S2", "S5", "S6", "S12", "S13", "M4", "NM4", "54", "61", "Filobus 92"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 15),
        .init(name: "Milano Porta Vittoria", lines: ["S1", "S2", "S5", "S6", "S12", "S13", "Filobus 91", "Filobus 93"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 16),
        .init(name: "Milano Rogoredo", lines: ["S1", "S2", "S9", "S12", "S13", "S19", "R31", "R34", "R38", "RE8", "RE11", "RE13", "M3", "NM3", "77", "88", "95", "140"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 17),
        .init(name: "San Donato Milanese", lines: ["S1", "S12"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 18),
        .init(name: "Borgolombardo", lines: ["S1", "S12", "132"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 19),
        .init(name: "San Giuliano Milanese", lines: ["S1", "S12", "121"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 20),
        .init(name: "Melegnano", lines: ["S1", "S12"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 21),
        .init(name: "San Zenone Al Lambro", lines: ["S1"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 22),
        .init(name: "Tavazzano", lines: ["S1"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 23),
        .init(name: "Lodi", lines: ["S1", "R38", "RE11", "RV"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 24),
        
        // Suburbano S2
        .init(name: "Mariano Comense", lines: ["S2", "R16", "z221"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 0),
        .init(name: "Cabiate", lines: ["S2", "R16"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 1),
        .init(name: "Meda", lines: ["S2", "R16"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 2),
        .init(name: "Seveso", lines: ["S2", "S4", "R16"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 3),
        .init(name: "Cesano Maderno", lines: ["S2", "S4", "S9", "R16", "z250"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 4),
        .init(name: "Boviso Masciago", lines: ["S2", "S4", "R16"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 5),
        .init(name: "Varedo", lines: ["S2", "S4", "R16"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 6),
        .init(name: "Palazzolo Milanese", lines: ["S2", "S4", "R16"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 7),
        .init(name: "Paderno Dugnano", lines: ["S2", "S4", "R16", "566"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 8),
        .init(name: "Cormano Cusano Milanino", lines: ["S2", "S4", "R16", "727"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 9),
        .init(name: "Milano Bruzzano Parco Nord", lines: ["S2", "S4", "R16"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 10),
        .init(name: "Milano Affori", lines: ["S2", "S4", "R16", "M3", "NM3", "35", "40", "41", "52", "70"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 11),
        .init(name: "Milano Bovisa", lines: ["S2", "S1", "S3", "S4", "S12", "S13", "R16", "R17", "R22", "R27", "RE1", "RE7", "RE13", "MXP1", "MXP2", "82", "Filobus 92"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 12),
        .init(name: "Milano Lancetti", lines: ["S2", "S1", "S5", "S6", "S12", "S13", "2", "Filobus 92"], typeOfInterchange: "tram.fill", branch: "Main", lineOrder: 13),
        .init(name: "Milano Porta Garibaldi", lines: ["S2", "S1", "S5", "S6", "S7", "S8", "S9", "S11", "S12", "S13", "AV", "R6", "R13", "R14", "R21", "R23", "R34", "RE2", "RE5", "RE6", "RE13", "MXP1", "M2", "NM2", "M5", "10", "33", "N25", "N26"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 14),
        .init(name: "Milano Repubblica", lines: ["S2", "S1", "S5", "S6", "S12", "S13", "M3", "NM3", "1", "9", "33", "43"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 15),
        .init(name: "Milano Porta Venezia", lines: ["S2", "S1", "S5", "S6", "S12", "S13", "M1", "NM1", "5", "9", "33"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 16),
        .init(name: "Milano Dateo", lines: ["S2", "S1", "S5", "S6", "S12", "S13", "M4", "NM4", "54", "61", "Filobus 92"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 17),
        .init(name: "Milano Porta Vittoria", lines: ["S2", "S1", "S5", "S6", "S12", "S13", "Filobus 91", "Filobus 93"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 18),
        .init(name: "Milano Rogoredo", lines: ["S2", "S1", "S9", "S12", "S13", "S19", "R31", "R34", "R38", "RE8", "RE11", "RE13", "M3", "NM3", "77", "88", "95", "140"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 19),
        
        // Suburbano S3
        .init(name: "Saronno", lines: ["S3", "S1", "S9", "R17", "R22", "R27", "RE1", "RE7", "RE13", "MXP1", "MXP2"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 0),
        .init(name: "Saronno Sud", lines: ["S3", "S1", "S9"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 1),
        .init(name: "Caronno Pertusella", lines: ["S3", "S1"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 2),
        .init(name: "Cesate", lines: ["S3", "S1"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 3),
        .init(name: "Garbagnate Milanese", lines: ["S3", "S1", "S13", "RE13"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 4),
        .init(name: "Garbagnate Parco Delle Groane", lines: ["S3", "S1"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 5),
        .init(name: "Bollate Nord", lines: ["S3", "S1"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 6),
        .init(name: "Bollate Centro", lines: ["S3", "S1", "S13", "RE13"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 7),
        .init(name: "Novate Milanese", lines: ["S3", "S1"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 8),
        .init(name: "Milano Quarto Oggiaro", lines: ["S3", "S1", "40"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 9),
        .init(name: "Milano Bovisa", lines: ["S3", "S1", "S2", "S4", "S12", "S13", "R16", "R17", "R22", "R27", "RE1", "RE7", "RE13", "MXP1", "MXP2", "82", "Filobus 92"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 10),
        .init(name: "Milano Domodossola", lines: ["S3", "S4", "R16", "R17", "R22", "R27", "RE1", "RE7", "MXP2", "M5", "1", "19"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 11),
        .init(name: "Milano Cadorna", lines: ["S3", "S4", "R16", "RE17", "R22", "R27", "RE1", "RE7", "MXP2", "M1", "NM1", "M2", "NM2", "1", "2", "50", "96", "97", "z602", "z603", "z6C3", "N25", "N26"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 12),
        
        // Suburbano S4
        .init(name: "Camnago - Lentate", lines: ["S4", "S11"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 0),
        .init(name: "Seveso", lines: ["S4", "S2", "R16"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 2),
        .init(name: "Cesano Maderno", lines: ["S4", "S2", "S9", "R16", "z250"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 3),
        .init(name: "Boviso Masciago", lines: ["S4", "S2", "R16"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 4),
        .init(name: "Varedo", lines: ["S4", "S2", "R16"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 5),
        .init(name: "Palazzolo Milanese", lines: ["S4", "S2", "R16"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 6),
        .init(name: "Paderno Dugnano", lines: ["S4", "S2", "R16", "566"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 7),
        .init(name: "Cormano Cusano Milanino", lines: ["S4", "S2", "R16", "727"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 8),
        .init(name: "Milano Bruzzano Parco Nord", lines: ["S4", "S2", "R16"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 9),
        .init(name: "Milano Affori", lines: ["S4", "S2", "R16", "M3", "NM3", "35", "40", "41", "52", "70"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 10),
        .init(name: "Milano Bovisa", lines: ["S4", "S1", "S2", "S3", "S12", "S13", "R16", "R17", "R22", "R27", "RE1", "RE7", "RE13", "MXP1", "MXP2", "82", "Filobus 92"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 11),
        .init(name: "Milano Domodossola", lines: ["S4", "S3", "R16", "R17", "R22", "R27", "RE1", "RE7", "MXP2", "M5", "1", "19"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 12),
        .init(name: "Milano Cadorna", lines: ["S4", "S3", "R16", "RE17", "R22", "R27", "RE1", "RE7", "MXP2", "M1", "NM1", "M2", "NM2", "1", "2", "50", "96", "97", "z602", "z603", "z6C3", "N25", "N26"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 13),
        
        // Suburbano S5
        .init(name: "Varese", lines: ["S5", "S40", "S50", "RE5"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 0),
        .init(name: "Gazzada Schianno Morazzone", lines: ["S5", "RE5"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 1),
        .init(name: "Castronno", lines: ["S5", "RE5"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 2),
        .init(name: "Albizzate Solbiate Arno", lines: ["S5", "RE5"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 3),
        .init(name: "Cavaria", lines: ["S5", "RE5"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 4),
        .init(name: "Gallarate", lines: ["S5", "S30", "S50", "R21", "R23", "RV", "RE4", "RE5", "MXP1"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 5),
        .init(name: "Busto Arsizio", lines: ["S5", "S50", "R21", "R23", "RV", "RE4", "RE5"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 6),
        .init(name: "Legnano", lines: ["S5", "R21", "RV", "RE5", "z601", "z602", "z611", "z627", "z636", "z642"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 7),
        .init(name: "Canegrate", lines: ["S5", "R21", "z611"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 8),
        .init(name: "Parabiago", lines: ["S5", "R21", "R23", "RE5", "z644"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 9),
        .init(name: "Vanzago Pogliano", lines: ["S5", "RE5"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 10),
        .init(name: "Rho", lines: ["S5", "S6", "S11", "RV", "431", "433", "z616"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 11),
        .init(name: "Rho Fiera Milano", lines: ["S5", "S6", "S11", "R21", "R23", "RE4", "RE5", "AV", "M1", "542", "561"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 12),
        .init(name: "Milano Certosa", lines: ["S5", "S6", "S11", "1", "12", "35", "40", "57"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 13),
        .init(name: "Milano Villapizzone", lines: ["S5", "S6", "S11", "R6", "RE2"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 14),
        .init(name: "Milano Lancetti", lines: ["S5", "S1", "S2", "S6", "S12", "S13", "2", "Filobus 92"], typeOfInterchange: "tram.fill", branch: "Main", lineOrder: 15),
        .init(name: "Milano Porta Garibaldi", lines: ["S5", "S1", "S2", "S6", "S7", "S8", "S9", "S11", "S12", "S13", "AV", "R6", "R13", "R14", "R21", "R23", "R34", "RE2", "RE5", "RE6", "RE13", "MXP1", "M2", "NM2", "M5", "10", "33", "N25", "N26"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 16),
        .init(name: "Milano Repubblica", lines: ["S5", "S1", "S2", "S6", "S12", "S13", "M3", "NM3", "1", "9", "33", "43"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 17),
        .init(name: "Milano Porta Venezia", lines: ["S5", "S1", "S2", "S6", "S12", "S13", "M1", "NM1", "5", "9", "33"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 18),
        .init(name: "Milano Dateo", lines: ["S5", "S1", "S2", "S6", "S12", "S13", "M4", "NM4", "54", "61", "Filobus 92"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 19),
        .init(name: "Milano Porta Vittoria", lines: ["S5", "S1", "S2", "S6", "S12", "S13", "Filobus 91", "Filobus 93"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 20),
        .init(name: "Milano Forlanini", lines: ["S5", "S6", "S9", "R38", "RE8", "RE13", "M4", "NM4", "12", "27", "45", "175", "973", "N27"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 21),
        .init(name: "Segrate", lines: ["S5", "S6"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 22),
        .init(name: "Pioltello Limito", lines: ["S5", "S6", "R4", "RE2", "RE6", "z402"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 23),
        .init(name: "Vignate", lines: ["S5", "S6", "R4", "z401"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 24),
        .init(name: "Melzo", lines: ["S5", "S6", "R4", "z401", "z404", "z407", "z411"], typeOfInterchange: "bus.fill", branch: "Main", lineOrder: 25),
        .init(name: "Pozzuolo Martesana", lines: ["S5", "S6", "R4"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 26),
        .init(name: "Trecella", lines: ["S5", "S6", "R4"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 27),
        .init(name: "Cassano D'Adda", lines: ["S5", "S6", "R4", "z405", "z407"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 28),
        .init(name: "Treviglio", lines: ["S5", "S6", "R2", "R4", "R6", "R7", "RE6"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 29),
        
        // Suburbano S6
        .init(name: "Novara", lines: ["S6", "R25", "RV"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 0),
        .init(name: "Trecate", lines: ["S6", "RV"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 1),
        .init(name: "Magenta", lines: ["S6", "RV", "z559", "z620", "z641", "z642", "z646"], typeOfInterchange: "bus.fill", branch: "Main", lineOrder: 2),
        .init(name: "Corbetta - S. Stefano Ticino", lines: ["S6", "RV", "z552", "z642"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 3),
        .init(name: "Vittuone - Arluno", lines: ["S6", "RV", "z622", "z643"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 4),
        .init(name: "Pregnana Milanese", lines: ["S6", "z616", "z649"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 5),
        .init(name: "Rho", lines: ["S6", "S5", "S11", "RV", "431", "433", "z616"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 6),
        .init(name: "Rho Fiera Milano", lines: ["S6", "S5", "S11", "R21", "R23", "RE4", "RE5", "AV", "M1", "542", "561"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 7),
        .init(name: "Milano Certosa", lines: ["S6", "S5", "S11", "1", "12", "35", "40", "57"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 8),
        .init(name: "Milano Villapizzone", lines: ["S6", "S5", "S11", "R6", "RE2"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 9),
        .init(name: "Milano Lancetti", lines: ["S6", "S1", "S2", "S5", "S12", "S13", "2", "Filobus 92"], typeOfInterchange: "tram.fill", branch: "Main", lineOrder: 10),
        .init(name: "Milano Porta Garibaldi", lines: ["S6", "S1", "S2", "S5", "S7", "S8", "S9", "S11", "S12", "S13", "AV", "R6", "R13", "R14", "R21", "R23", "R34", "RE2", "RE5", "RE6", "RE13", "MXP1", "M2", "NM2", "M5", "10", "33", "N25", "N26"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 11),
        .init(name: "Milano Repubblica", lines: ["S6", "S1", "S2", "S5", "S12", "S13", "M3", "NM3", "1", "9", "33", "43"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 12),
        .init(name: "Milano Porta Venezia", lines: ["S6", "S1", "S2", "S5", "S12", "S13", "M1", "NM1", "5", "9", "33"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 13),
        .init(name: "Milano Dateo", lines: ["S6", "S1", "S2", "S5", "S12", "S13", "M4", "NM4", "54", "61", "Filobus 92"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 14),
        .init(name: "Milano Porta Vittoria", lines: ["S6", "S1", "S2", "S5", "S12", "S13", "Filobus 91", "Filobus 93"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 15),
        .init(name: "Milano Forlanini", lines: ["S6", "S5", "S9", "R38", "RE8", "RE13", "M4", "NM4", "12", "27", "45", "175", "973", "N27"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 16),
        .init(name: "Segrate", lines: ["S6", "S5"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 17),
        .init(name: "Pioltello Limito", lines: ["S6", "S5", "R4", "RE2", "RE6", "z402"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 18),
        .init(name: "Vignate", lines: ["S6", "S5", "R4", "z401"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 19),
        .init(name: "Melzo", lines: ["S6", "S5", "R4", "z401", "z404", "z407", "z411"], typeOfInterchange: "bus.fill", branch: "Main", lineOrder: 20),
        .init(name: "Pozzuolo Martesana", lines: ["S6", "S5", "R4"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 21),
        .init(name: "Trecella", lines: ["S6", "S5", "R4"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 22),
        .init(name: "Cassano D'Adda", lines: ["S6", "S5", "R4", "z405", "z407"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 23),
        .init(name: "Treviglio", lines: ["S6", "S5", "R2", "R4", "R6", "R7", "RE6"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 24),
        
        // Suburbano S7
        .init(name: "Milano Porta Garibaldi", lines: ["S7", "S1", "S2", "S5", "S6", "S8", "S9", "S11", "S12", "S13", "AV", "R6", "R13", "R14", "R21", "R23", "R34", "RE2", "RE5", "RE6", "RE13", "MXP1", "M2", "NM2", "M5", "10", "33", "N25", "N26"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 0),
        .init(name: "Milano Greco Pirelli", lines: ["S7", "S8", "S9", "S11", "R4", "R13", "R14", "R38", "RE13", "RE80", "7", "52", "81", "86", "174"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 1),
        .init(name: "Sesto S. Giovanni", lines: ["S7", "S8", "S9", "S11", "R13", "R14", "RE8", "RE80", "M1", "NM1", "700", "702", "712", "727", "729"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 2),
        .init(name: "Monza", lines: ["S7", "S8", "S9", "S11", "R7", "R13", "R14", "RE8", "RE13", "RE80", "z201", "z203", "z205", "z206", "z208", "z211", "z213", "z221", "z222", "z228"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 3),
        .init(name: "Monza Sobborghi", lines: ["S7"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 4),
        .init(name: "Villasanta", lines: ["S7"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 5),
        .init(name: "Buttafava", lines: ["S7"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 6),
        .init(name: "Biassono - Lesmo Parco", lines: ["S7"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 7),
        .init(name: "Macherio - Canonica", lines: ["S7"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 8),
        .init(name: "Triuggio - Ponte Albiate", lines: ["S7", "z233"], typeOfInterchange: "bus.fill", branch: "Main", lineOrder: 9),
        .init(name: "Carate Calò", lines: ["S7"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 10),
        .init(name: "Villa Raverio", lines: ["S7"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 11),
        .init(name: "Besana", lines: ["S7", "z323", "z242"], typeOfInterchange: "bus.fill", branch: "Main", lineOrder: 12),
        .init(name: "Renate - Veduggio", lines: ["S7", "z242"], typeOfInterchange: "bus.fill", branch: "Main", lineOrder: 13),
        .init(name: "Cassago Nibionno Bulciago", lines: ["S7"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 14),
        .init(name: "Costa Masnaga", lines: ["S7"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 15),
        .init(name: "Molteno", lines: ["S7", "R18"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 16),
        .init(name: "Oggiono", lines: ["S7", "R18"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 17),
        .init(name: "Sala Al Barro - Galbiate", lines: ["S7", "R18"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 18),
        .init(name: "Civate", lines: ["S7", "R18"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 19),
        .init(name: "Valmadrera", lines: ["S7", "R18"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 20),
        .init(name: "Lecco", lines: ["S7", "S8", "R7", "R13", "R18", "RE8"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 21),
        
        // Suburbano S8
        .init(name: "Milano Porta Garibaldi", lines: ["S8", "S1", "S2", "S5", "S6", "S7", "S9", "S11", "S12", "S13", "AV", "R6", "R13", "R14", "R21", "R23", "R34", "RE2", "RE5", "RE6", "RE13", "MXP1", "M2", "NM2", "M5", "10", "33", "N25", "N26"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 0),
        .init(name: "Milano Greco Pirelli", lines: ["S8", "S7", "S9", "S11", "R4", "R13", "R14", "R38", "RE13", "RE80", "7", "52", "81", "86", "174"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 1),
        .init(name: "Sesto S. Giovanni", lines: ["S8", "S7", "S9", "S11", "R13", "R14", "RE8", "RE80", "M1", "NM1", "700", "702", "712", "727", "729"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 2),
        .init(name: "Monza", lines: ["S8", "S7", "S9", "S11", "R7", "R13", "R14", "RE8", "RE13", "RE80", "z201", "z203", "z205", "z206", "z208", "z211", "z213", "z221", "z222", "z228"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 3),
        .init(name: "Arcore", lines: ["S8", "R13", "R14", "z208"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 4),
        .init(name: "Carnate Usmate", lines: ["S8", "R13", "R14", "RE8"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 5),
        .init(name: "Osnago", lines: ["S8"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 6),
        .init(name: "Cernusco - Merate", lines: ["S8", "R13", "RE8"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 7),
        .init(name: "Olgiate - Calco - Brivio", lines: ["S8"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 8),
        .init(name: "Airuno", lines: ["S8"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 9),
        .init(name: "Calolziocorte Olginate", lines: ["S8", "R7", "RE8"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 10),
        .init(name: "Lecco Maggianico", lines: ["S8"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 11),
        .init(name: "Lecco", lines: ["S8", "S7", "R7", "R13", "R18", "RE8"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 12),
        
        // Suburbano S9
        .init(name: "Saronno", lines: ["S9", "S1", "S3", "R17", "R22", "R27", "RE1", "RE7", "RE13", "MXP1", "MXP2"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 0),
        .init(name: "Saronno Sud", lines: ["S9", "S1", "S3"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 1),
        .init(name: "Ceriano Laghetto - Solaro", lines: ["S9"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 2),
        .init(name: "Cesano Maderno", lines: ["S9", "S2", "S4", "R16"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 3),
        .init(name: "Seveso Baruccana", lines: ["S9"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 4),
        .init(name: "Seregno", lines: ["S9", "S11", "RE13", "RE80", "z233"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 5),
        .init(name: "Desio", lines: ["S9", "S11", "RE80", "z250", "z251"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 6),
        .init(name: "Lissone - Muggiò", lines: ["S9", "S11", "z227", "z238"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 7),
        .init(name: "Monza", lines: ["S9", "S7", "S8", "S11", "R7", "R13", "R14", "RE8", "RE13", "RE80", "z201", "z203", "z205", "z206", "z208", "z211", "z213", "z221", "z222", "z228"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 8),
        .init(name: "Sesto S. Giovanni", lines: ["S9", "S7", "S8", "S11", "R13", "R14", "RE8", "RE80", "M1", "NM1", "700", "702", "712", "727", "729"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 9),
        .init(name: "Milano Greco Pirelli", lines: ["S9", "S7", "S8", "S11", "R4", "R13", "R14", "R38", "RE13", "RE80", "7", "52", "81", "86", "174"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 10),
        .init(name: "Milano Lambrate", lines: ["S9", "R4", "R6", "R7", "R34", "R38", "RE2", "RE6", "RE8", "RE11", "RE13", "RV", "M2", "NM2", "19", "39", "45", "54", "81", "93", "175", "924"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 11),
        .init(name: "Milano Forlanini", lines: ["S9", "S5", "S6", "R38", "RE8", "RE13", "M4", "NM4", "12", "27", "45", "175", "973", "N27"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 12),
        .init(name: "Milano Scalo Romana", lines: ["S9", "S19", "R31", "M3", "NM3", "65", "Filobus 90", "Filobus 91", "Filobus 92"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 13),
        .init(name: "Milano Tibaldi", lines: ["S9", "S19", "R31", "15", "59", "Filobus 90", "Filobus 91"], typeOfInterchange: "tram.fill", branch: "Main", lineOrder: 14),
        .init(name: "Milano Romolo", lines: ["S9", "S19", "R31", "M2", "NM2", "47", "Filobus 90", "Filobus 91", "71", "324", "325", "z553"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 15),
        .init(name: "Milano San Cristoforo", lines: ["S9", "S19", "R31", "M4", "NM4", "47", "49", "95", "324", "325", "326", "351", "z553"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 16),
        .init(name: "Corsico", lines: ["S9", "S19", "R31", "326"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 17),
        .init(name: "Cesano Boscone", lines: ["S9", "S19", "R31"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 18),
        .init(name: "Trezzano Sul Naviglio", lines: ["S9", "S19", "R31"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 19),
        .init(name: "Gaggiano", lines: ["S9", "S19", "R31", "z557"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 20),
        .init(name: "Albairate Vermezzo", lines: ["S9", "S19", "R31", "z554"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 21),
        
        // Suburbano S11
        .init(name: "Rho", lines: ["S11", "S5", "S6", "RV", "431", "433", "z616"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 0),
        .init(name: "Rho Fiera Milano", lines: ["S11", "S5", "S6", "R21", "R23", "RE4", "RE5", "AV", "M1", "542", "561"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 1),
        .init(name: "Milano Certosa", lines: ["S11", "S5", "S6", "1", "12", "35", "40", "57"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 2),
        .init(name: "Milano Villapizzone", lines: ["S11", "S5", "S6", "R6", "RE2"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 3),
        .init(name: "Milano Porta Garibaldi", lines: ["S11", "S1", "S2", "S5", "S6", "S7", "S8", "S9", "S12", "S13", "AV", "R6", "R13", "R14", "R21", "R23", "R34", "RE2", "RE5", "RE6", "RE13", "MXP1", "M2", "NM2", "M5", "10", "33", "N25", "N26"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 4),
        .init(name: "Milano Greco Pirelli", lines: ["S11", "S7", "S8", "S9", "R4", "R13", "R14", "R38", "RE13", "RE80", "7", "52", "81", "86", "174"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 5),
        .init(name: "Sesto S. Giovanni", lines: ["S11", "S7", "S8", "S9", "R13", "R14", "RE8", "RE80", "M1", "NM1", "700", "702", "712", "727", "729"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 6),
        .init(name: "Monza", lines: ["S11", "S7", "S8", "S9", "R7", "R13", "R14", "RE8", "RE13", "RE80", "z201", "z203", "z205", "z206", "z208", "z211", "z213", "z221", "z222", "z228"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 7),
        .init(name: "Lissone - Muggiò", lines: ["S11", "S9", "z227", "z238"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 8),
        .init(name: "Desio", lines: ["S11", "S9", "RE80", "z250", "z251"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 9),
        .init(name: "Seregno", lines: ["S11", "S9", "RE13", "RE80", "z233"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 10),
        .init(name: "Camnago - Lentate", lines: ["S11", "S4"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 11),
        .init(name: "Carimate", lines: ["S11"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 12),
        .init(name: "Cantù - Cermenate", lines: ["S11", "RE80"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 13),
        .init(name: "Cucciago", lines: ["S11"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 14),
        .init(name: "Como Camerlata", lines: ["S11", "S10", "S40", "R17", "R18", "RE7", "RE13", "RE80"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 15),
        .init(name: "Como San Giovanni", lines: ["S11", "S10", "S40", "R18", "RE13", "RE80"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 16),
        
        // Suburbano S12
        .init(name: "Milano Bovisa", lines: ["S12", "S1", "S2", "S3", "S4", "S13", "R16", "R17", "R22", "R27", "RE1", "RE7", "RE13", "MXP1", "MXP2", "82", "Filobus 92"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 0),
        .init(name: "Milano Lancetti", lines: ["S12", "S1", "S2", "S5", "S6", "S13", "2", "Filobus 92"], typeOfInterchange: "tram.fill", branch: "Main", lineOrder: 1),
        .init(name: "Milano Porta Garibaldi", lines: ["S12", "S1", "S2", "S5", "S6", "S7", "S8", "S9", "S11", "S13", "AV", "R6", "R13", "R14", "R21", "R23", "R34", "RE2", "RE5", "RE6", "RE13", "MXP1", "M2", "NM2", "M5", "10", "33", "N25", "N26"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 2),
        .init(name: "Milano Repubblica", lines: ["S12", "S1", "S2", "S5", "S6", "S13", "M3", "NM3", "1", "9", "33", "43"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 3),
        .init(name: "Milano Porta Venezia", lines: ["S12", "S1", "S2", "S5", "S6", "S13", "M1", "NM1", "5", "9", "33"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 4),
        .init(name: "Milano Dateo", lines: ["S12", "S1", "S2", "S5", "S6", "S13", "M4", "NM4", "54", "61", "Filobus 92"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 5),
        .init(name: "Milano Porta Vittoria", lines: ["S12", "S1", "S2", "S5", "S6", "S13", "Filobus 91", "Filobus 93"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 6),
        .init(name: "Milano Rogoredo", lines: ["S12", "S1", "S2", "S9", "S13", "S19", "R31", "R34", "R38", "RE8", "RE11", "RE13", "M3", "NM3", "77", "88", "95", "140"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 7),
        .init(name: "San Donato Milanese", lines: ["S12", "S1"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 8),
        .init(name: "Borgolombardo", lines: ["S12", "S1", "132"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 9),
        .init(name: "San Giuliano Milanese", lines: ["S12", "S1", "121"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 10),
        .init(name: "Melegnano", lines: ["S12", "S1"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 11),
        
        // Suburbano S13
        .init(name: "Garbagnate Milanese", lines: ["S13", "S1", "S3", "RE13"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 0),
        .init(name: "Bollate Centro", lines: ["S13", "S1", "S3", "RE13"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 1),
        .init(name: "Milano Bovisa", lines: ["S13", "S1", "S2", "S3", "S4", "S12", "R16", "R17", "R22", "R27", "RE1", "RE7", "RE13", "MXP1", "MXP2", "82", "Filobus 92"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 2),
        .init(name: "Milano Lancetti", lines: ["S13", "S1", "S2", "S5", "S6", "S12", "2", "Filobus 92"], typeOfInterchange: "tram.fill", branch: "Main", lineOrder: 3),
        .init(name: "Milano Porta Garibaldi", lines: ["S13", "S1", "S2", "S5", "S6", "S7", "S8", "S9", "S11", "S12", "AV", "R6", "R13", "R14", "R21", "R23", "R34", "RE2", "RE5", "RE6", "RE13", "MXP1", "M2", "NM2", "M5", "10", "33", "N25", "N26"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 4),
        .init(name: "Milano Repubblica", lines: ["S13", "S1", "S2", "S5", "S6", "S12", "M3", "NM3", "1", "9", "33", "43"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 5),
        .init(name: "Milano Porta Venezia", lines: ["S13", "S1", "S2", "S5", "S6", "S12", "M1", "NM1", "5", "9", "33"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 6),
        .init(name: "Milano Dateo", lines: ["S13", "S1", "S2", "S5", "S6", "S12", "M4", "NM4", "54", "61", "Filobus 92"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 7),
        .init(name: "Milano Porta Vittoria", lines: ["S13", "S1", "S2", "S5", "S6", "S12", "Filobus 91", "Filobus 93"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 8),
        .init(name: "Milano Rogoredo", lines: ["S13", "S1", "S2", "S9", "S12", "S19", "R31", "R34", "R38", "RE8", "RE11", "RE13", "M3", "NM3", "77", "88", "95", "140"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 9),
        .init(name: "Locate Triulzi", lines: ["S13", "220"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 10),
        .init(name: "Pieve Emanuele", lines: ["S13", "220", "222", "328"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 11),
        .init(name: "Villamaggiore", lines: ["S13"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 12),
        .init(name: "Certosa di Pavia", lines: ["S13"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 13),
        .init(name: "Pavia", lines: ["S13", "R34", "R35", "R36", "R37", "RE13", "RV"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 14),
        
        // Suburbano S19
        .init(name: "Milano Rogoredo", lines: ["S19", "S1", "S2", "S9", "S12", "S13", "R31", "R34", "R38", "RE8", "RE11", "RE13", "M3", "NM3", "77", "88", "95", "140"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 0),
        .init(name: "Milano Scalo Romana", lines: ["S19", "S9", "R31", "M3", "NM3", "65", "Filobus 90", "Filobus 91", "Filobus 92"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 1),
        .init(name: "Milano Tibaldi", lines: ["S19", "S9", "R31", "15", "59", "Filobus 90", "Filobus 91"], typeOfInterchange: "tram.fill", branch: "Main", lineOrder: 2),
        .init(name: "Milano Romolo", lines: ["S19", "S9", "R31", "M2", "NM2", "47", "Filobus 90", "Filobus 91", "71", "324", "325", "z553"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 3),
        .init(name: "Milano San Cristoforo", lines: ["S19", "S9", "R31", "M4", "NM4", "47", "49", "95", "324", "325", "326", "351", "z553"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 4),
        .init(name: "Corsico", lines: ["S19", "S9", "R31", "326"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 5),
        .init(name: "Cesano Boscone", lines: ["S19", "S9", "R31"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 6),
        .init(name: "Trezzano Sul Naviglio", lines: ["S19", "S9", "R31"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 7),
        .init(name: "Gaggiano", lines: ["S19", "S9", "R31", "z557"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 8),
        .init(name: "Albairate Vermezzo", lines: ["S19", "S9", "R31", "z554"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 9),
        
        // Suburbano S31
        .init(name: "Brescia", lines: ["S31", "R1", "R3", "R4", "R5", "R7", "R8", "RE3", "RE6", "AV"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 0),
        .init(name: "Brescia Borgo San Giovanni", lines: ["S31", "R3"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 1),
        .init(name: "Brescia Violino", lines: ["S31", "R3"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 2),
        .init(name: "Castegnato", lines: ["S31", "R3"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 3),
        .init(name: "Paderno Franciacorta", lines: ["S31", "R3"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 4),
        .init(name: "Passirano", lines: ["S31", "R3"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 5),
        .init(name: "Bornato Calino", lines: ["S31", "R3", "R9"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 6),
        .init(name: "Borgonato Adro", lines: ["S31", "R3"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 7),
        .init(name: "Provaglio Timoline", lines: ["S31", "R3"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 8),
        .init(name: "Iseo", lines: ["S31", "R3", "R9", "RE3"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 9),
    ]
    
    static let malpensaExpressInterchanges: [InterchangeInfo] = [
        // MALPENSA EXPRESS LINES
        
        // Malpensa Express 1
        .init(name: "Gallarate", lines: ["MXP1", "S5", "S30", "S50", "R21", "R23", "RV", "RE4", "RE5"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 0),
        .init(name: "Malpensa Aereoporto T2", lines: ["MXP1", "Aereoporto", "S50", "MXP2"], typeOfInterchange: "airplane.departure", branch: "Main", lineOrder: 1),
        .init(name: "Malpensa Aereoporto T1", lines: ["MXP1", "Aereoporto", "S50", "MXP2"], typeOfInterchange: "airplane.departure", branch: "Main", lineOrder: 2),
        .init(name: "Ferno - Lonate Pozzolo", lines: ["MXP1", "S50"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 3),
        .init(name: "Busto Arsizio Nord", lines: ["MXP1", "S50", "R27", "MXP2"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 4),
        .init(name: "Castellanza", lines: ["MXP1", "R27"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 5),
        .init(name: "Rescaldina", lines: ["MXP1", "R27"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 6),
        .init(name: "Saronno", lines: ["MXP1", "S1", "S3", "S9", "R17", "R22", "R27", "RE1", "RE7", "RE13", "MXP2"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 7),
        .init(name: "Milano Bovisa", lines: ["MXP1", "S1", "S2", "S3", "S4", "S12", "S13", "R16", "R17", "R22", "R27", "RE1", "RE7", "RE13", "MXP2", "82", "Filobus 92"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 8),
        .init(name: "Milano Porta Garibaldi", lines: ["MXP1", "S1", "S2", "S5", "S6", "S7", "S8", "S9", "S11", "S12", "S13", "AV", "R6", "R13", "R14", "R21", "R23", "R34", "RE2", "RE5", "RE6", "RE13", "M2", "NM2", "M5", "10", "33", "N25", "N26"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 9),
        .init(name: "Milano Centrale", lines: ["MXP1", "AV", "R4", "RE2", "RE4", "RE6", "RE8", "RE11", "RE13", "RE80", "M3", "NM3", "M2", "NM2", "5", "9", "10", "42", "60", "81", "87", "Filobus 90", "Filobus 91", "Filobus 92", "728", "N25", "N26"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 10),
        
        // Malpensa Express 2
        .init(name: "Malpensa Aereoporto T2", lines: ["MXP2", "Aereoporto", "S50", "MXP1"], typeOfInterchange: "airplane.departure", branch: "Main", lineOrder: 0),
        .init(name: "Malpensa Aereoporto T1", lines: ["MXP2", "Aereoporto", "S50", "MXP1"], typeOfInterchange: "airplane.departure", branch: "Main", lineOrder: 1),
        .init(name: "Busto Arsizio Nord", lines: ["MXP2", "S50", "R27", "MXP1"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 2),
        .init(name: "Saronno", lines: ["MXP2", "S1", "S3", "S9", "R17", "R22", "R27", "RE1", "RE7", "RE13", "MXP1"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 3),
        .init(name: "Milano Bovisa", lines: ["MXP2", "S1", "S2", "S3", "S4", "S12", "S13", "R16", "R17", "R22", "R27", "RE1", "RE7", "RE13", "MXP1", "82", "Filobus 92"], typeOfInterchange: "lightrail", branch: "Main", lineOrder: 4),
        .init(name: "Milano Domodossola", lines: ["MXP2", "S3", "S4", "R16", "R17", "R22", "R27", "RE1", "RE7", "M5", "1", "19"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 5),
        .init(name: "Milano Cadorna", lines: ["MXP2", "S3", "S4", "R16", "RE17", "R22", "R27", "RE1", "RE7", "M1", "NM1", "M2", "NM2", "1", "2", "50", "96", "97", "z602", "z603", "z6C3", "N25", "N26"], typeOfInterchange: "tram.fill.tunnel", branch: "Main", lineOrder: 6),
    ]

    static func getMetroInterchanges(line: String) -> [InterchangeInfo] {
        return interchangesMetro.filter { $0.lines.contains(line) }
    }
    
    static func getSuburbanInterchanges(line: String) -> [InterchangeInfo] {
        return suburbanInterchanges.filter { $0.lines.contains(line) }
    }
    
    static func getMalpensaExpressInterchanges(line: String) -> [InterchangeInfo] {
        return malpensaExpressInterchanges.filter { $0.lines.contains(line) }
    }
}
